name: Scrape Pokémon GO Store

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行
  workflow_dispatch:      # 可手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      PROXY_USER: ${{ secrets.PROXY_USER }}
      PROXY_PASS: ${{ secrets.PROXY_PASS }}
      PROXY_HOST: ${{ secrets.PROXY_HOST }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}

    steps:
    - name: Checkout repository with token
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}  # 用你自己的 PAT 确保可以 push

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Ensure images folder exists
      run: |
        mkdir -p images
        touch images/.keep

    - name: Run scraper
      run: python PokemonGoInfo.py

    - name: Run extractor
      run: python extractInfo.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "TeemoBot"
        git config user.email "teemobot@example.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

        git add data.json webstore_items_limited.csv webstore_items_limited.json images/
        git commit -m "Update store data and images [auto]" || echo "No changes"
        git push origin HEAD:${{ github.ref_name }}

